// Code generated by "stringer -type=Interval"; DO NOT EDIT.

package snapshot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Minute-0]
	_ = x[Hour-1]
	_ = x[Day-2]
	_ = x[Week-3]
	_ = x[Month-4]
	_ = x[Year-5]
	_ = x[nIntervals-6]
}

const _Interval_name = "MinuteHourDayWeekMonthYearnIntervals"

var _Interval_index = [...]uint8{0, 6, 10, 13, 17, 22, 26, 36}

func (i Interval) String() string {
	if i < 0 || i >= Interval(len(_Interval_index)-1) {
		return "Interval(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interval_name[_Interval_index[i]:_Interval_index[i+1]]
}
